import addonCrafts from './addonCrafts-min.png'
import addonNightLife from './addonNightLife-min.png'
import addonOnsen from './addonOnsen-min.png'
import addonSumo from './addonSumo-min.png'
import hero from './hero-min.jpg'
import alps from './alps-min.jpg'
import aroundfiju from './aroundfiju-min.jpg'
import autumnPkg from './autumnPkg-min.png'
import breezeOfc from './breezeOfc-min.png'
import breezeLogo from './breezeLogo.png'
import bullettrain from './bullettrain.png'
import citystreets from './citystreets.png'
import islandbreeze from './islandbreeze.png'
import japanAlps from './japanAlps.png'
import japannight from './japannight.png'
import jpDineing from './jpDineing-min.png'
import jpFestival from './jpFestival-min.png'
import kimono from './kimono.png'
import kyoto from './kyoto-min.jpg'
import kyoutobamboo from './kyoutobamboo.png'
import kyoutoBlog from './kyoutoBlog-min.png'
import mtfuji from './mtfuji.png'
import nighttokyojpg from './nighttokyojpg-min.jpg'
import office2 from './office.png'
import okinawa from './okinawa.png'
import packingList from './packignList-min.png'
import pkgA from './pkgA-min.png'
import riverredbridge from './riverredbridge.png'
import snowboarding from './snowboarding.png'
import springPkg from './springPkg-min.png'
import summerPkg from './summerPkg-min.png'
import winterPkg from './winterPkg-min.png'
import temple from './temple.png'


export {addonCrafts,addonNightLife,addonOnsen,addonSumo,alps,aroundfiju,autumnPkg,breezeLogo,breezeOfc,bullettrain,citystreets,hero,islandbreeze,japanAlps,japannight,jpDineing,jpFestival,kimono,kyoto,kyoutoBlog,kyoutobamboo,mtfuji,nighttokyojpg,office2,okinawa,packingList,pkgA,riverredbridge,snowboarding,springPkg,summerPkg,winterPkg,temple}